lab:
  description: ''
  notes: ''
  title: Switch Configurations
  version: 0.1.0
links: []
nodes:
  - boot_disk_size: 0
    configuration: |-
      Building configuration...

      Current configuration : 2960 bytes
      !
      ! Last configuration change at 07:06:23 UTC Tue Aug 22 2023
      !
      version 15.2
      service timestamps debug datetime msec
      service timestamps log datetime msec
      no service password-encryption
      service compress-config
      !
      hostname inserthostname_here
      !
      boot-start-marker
      boot-end-marker
      !
      !
      no logging console
      !
      no aaa new-model
      !
      !
      !
      !
      !
      !
      !
      !
      ip cef
      ipv6 unicast-routing
      ipv6 cef
      !
      !
      !
      spanning-tree mode pvst
      spanning-tree extend system-id
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      interface GigabitEthernet0/0
       negotiation auto
      !
      interface GigabitEthernet0/1
       negotiation auto
      !
      interface GigabitEthernet0/2
       negotiation auto
      !
      interface GigabitEthernet0/3
       negotiation auto
      !
      interface GigabitEthernet1/0
       negotiation auto
      !
      interface GigabitEthernet1/1
       negotiation auto
      !
      interface GigabitEthernet1/2
       negotiation auto
      !
      interface GigabitEthernet1/3
       negotiation auto
      !
      ip forward-protocol nd
      !
      ip http server
      ip http secure-server
      !
      ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
      ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
      !
      !
      !
      !
      !
      !
      control-plane
      !
      banner exec ^CCCC
      IOSv - Cisco Systems Confidential -

      Supplemental End User License Restrictions

      This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

      By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
      ^C
      banner incoming ^CCCC
      IOSv - Cisco Systems Confidential -

      Supplemental End User License Restrictions

      This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

      By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
      ^C
      banner login ^CCCC
      IOSv - Cisco Systems Confidential -

      Supplemental End User License Restrictions

      This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

      By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
      ^C
      !
      line con 0
      line aux 0
      line vty 0 4
       login
      !
      !
      end
    cpu_limit: 100
    cpus: 0
    data_volume: 0
    hide_links: false
    id: n0
    label: ASw1
    node_definition: iosvl2
    ram: 768
    tags: []
    x: 20
    y: 193
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet1/0
        slot: 4
        type: physical
      - id: i6
        label: GigabitEthernet1/1
        slot: 5
        type: physical
      - id: i7
        label: GigabitEthernet1/2
        slot: 6
        type: physical
      - id: i8
        label: GigabitEthernet1/3
        slot: 7
        type: physical
  - boot_disk_size: 0
    configuration: |-
      Building configuration...

      Current configuration : 2986 bytes
      !
      ! Last configuration change at 06:58:25 UTC Tue Aug 22 2023
      !
      version 15.2
      service timestamps debug datetime msec
      service timestamps log datetime msec
      no service password-encryption
      service compress-config
      !
      hostname ASw2
      !
      boot-start-marker
      boot-end-marker
      !
      !
      no logging console
      !
      no aaa new-model
      !
      !
      !
      !
      !
      !
      !
      !
      ip cef
      ipv6 unicast-routing
      ipv6 cef
      !
      !
      !
      spanning-tree mode pvst
      spanning-tree extend system-id
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      !
      interface GigabitEthernet0/0
       negotiation auto
      !
      interface GigabitEthernet0/1
       negotiation auto
      !
      interface GigabitEthernet0/2
       negotiation auto
      !
      interface GigabitEthernet0/3
       negotiation auto
      !
      interface GigabitEthernet1/0
       negotiation auto
      !
      interface GigabitEthernet1/1
       negotiation auto
      !
      interface GigabitEthernet1/2
       negotiation auto
      !
      interface GigabitEthernet1/3
       negotiation auto
      !
      interface Vlan23
       no ip address
       shutdown
      !
      ip forward-protocol nd
      !
      ip http server
      ip http secure-server
      !
      ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
      ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
      !
      !
      !
      !
      !
      !
      control-plane
      !
      banner exec ^CCC
      IOSv - Cisco Systems Confidential -

      Supplemental End User License Restrictions

      This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

      By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
      ^C
      banner incoming ^CCC
      IOSv - Cisco Systems Confidential -

      Supplemental End User License Restrictions

      This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

      By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
      ^C
      banner login ^CCC
      IOSv - Cisco Systems Confidential -

      Supplemental End User License Restrictions

      This IOSv software is provided AS-IS without warranty of any kind. Under no circumstances may this software be used separate from the Cisco Modeling Labs Software that this software was provided with, or deployed or used as part of a production environment.

      By using the software, you agree to abide by the terms and conditions of the Cisco End User License Agreement at http://www.cisco.com/go/eula. Unauthorized use or distribution of this software is expressly prohibited.
      ^C
      !
      line con 0
      line aux 0
      line vty 0 4
       login
      !
      !
      end
    cpu_limit: 100
    cpus: 0
    data_volume: 0
    hide_links: false
    id: n1
    label: ASw2
    node_definition: iosvl2
    ram: 768
    tags: []
    x: 92
    y: 193
    interfaces:
      - id: i0
        label: Loopback0
        type: loopback
      - id: i1
        label: GigabitEthernet0/0
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet0/1
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet0/2
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet0/3
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet1/0
        slot: 4
        type: physical
      - id: i6
        label: GigabitEthernet1/1
        slot: 5
        type: physical
      - id: i7
        label: GigabitEthernet1/2
        slot: 6
        type: physical
      - id: i8
        label: GigabitEthernet1/3
        slot: 7
        type: physical
  - boot_disk_size: 16
    configuration: |-
      # this is a shell script which will be sourced at boot
      hostname PC-A
      sudo ifconfig eth0 hw ether a0:a0:a0:a0:a0:a0
      # configurable user account
      USERNAME=cisco
      PASSWORD=cisco
      # network config
      ip addr add 192.168.1.11/24 dev eth0 || true
      ip route add default via 192.168.1.1 || true
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n2
    label: PC-A
    node_definition: desktop
    ram: 512
    tags: []
    x: 21
    y: 117
    interfaces:
      - id: i0
        label: eth0
        slot: 0
        type: physical
  - boot_disk_size: 16
    configuration: |-
      # this is a shell script which will be sourced at boot
      hostname PC-B
      sudo ifconfig eth0 hw ether b0:b0:b0:b0:b0:b0
      # configurable user account
      USERNAME=cisco
      PASSWORD=cisco
      # network config
      ip addr add 192.168.1.12/24 dev eth0 || true
      ip route add default via 192.168.1.1 || true
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n3
    label: PC-B
    node_definition: desktop
    ram: 512
    tags: []
    x: 90
    y: 117
    interfaces:
      - id: i0
        label: eth0
        slot: 0
        type: physical
  - boot_disk_size: 16
    configuration: |-
      # this is a shell script which will be sourced at boot
      hostname PC-C
      sudo ifconfig eth0 hw ether c0:c0:c0:c0:c0:c0
      # configurable user account
      USERNAME=cisco
      PASSWORD=cisco
      # network config
      ip addr add 192.168.100.11/24 dev eth0 || true
      ip route add default via 192.168.100.1 || true
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n4
    label: PC-C
    node_definition: desktop
    ram: 512
    tags: []
    x: 152
    y: 117
    interfaces:
      - id: i0
        label: eth0
        slot: 0
        type: physical
  - boot_disk_size: 16
    configuration: |-
      # this is a shell script which will be sourced at boot
      hostname PC-D
      sudo ifconfig eth0 hw ether d0:d0:d0:d0:d0:d0
      # configurable user account
      USERNAME=cisco
      PASSWORD=cisco
      # network config
      ip addr add 192.168.100.12/24 dev eth0 || true
      ip route add default via 192.168.100.1 || true
    cpu_limit: 100
    cpus: 1
    data_volume: 0
    hide_links: false
    id: n5
    label: PC-D
    node_definition: desktop
    ram: 512
    tags: []
    x: 222
    y: 117
    interfaces:
      - id: i0
        label: eth0
        slot: 0
        type: physical
